# To install this environment:
# micromamba create -f environment.yaml -y
name: mu-star
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip:
      - -e .
      - nismod-snail
  - geopandas
  - hatchling
  - jupyter
  - netCDF4
  - notebook
  - numpy
  - matplotlib
  - pyarrow
  - pytest
  - bioconda::snakemake
  - tqdm
  - xarray
  - zarr
  - contextily
  - matplotlib_map_utils
  - 'duckdb==1.3.2'
  - 'pyarrow==21.0.0'
  - geoarrow-pyarrow
  - 'ibis-framework[duckdb,geospatial]'