# To install this environment:
# micromamba create -f environment.yaml -y
name: mu-star
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip:
      - -e .
      - nismod-snail
  - geopandas
  - hatchling
  - highspy
  - jupyter
  - matplotlib
  - nbstripout
  - netCDF4
  - networkx
  - notebook
  - numpy>=1.26,<2
  - openpyxl
  - osmnx>=2
  - pandas>=2,<3
  - plotly>=6
  - pre-commit
  - pyarrow
  - pypsa>=0.30,<0.31
  - pytest
  - scipy
  - shapely
  - bioconda::snakemake
  - tqdm
  - xarray
  - zarr
