# To install this environment:
# micromamba create -f environment.yaml -y
name: mu-star
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip:
      - -e .[dev]
      - nismod-snail
      - osmium
  - geopandas
  - hatchling
  - jupyter
  - netCDF4
  - notebook
  - numpy
  - matplotlib
  - pyarrow
  - pytest
  - bioconda::snakemake
  - tqdm
  - xarray
  - zarr
