# This file contains configuration options for mu-star analysis.
# These values are used by snakemake rules in the `workflow/` directory.

paths:
  # Update these values when the shared data layout is finalised.
  raw_local_econ_data: "../catalogue/datasets/mauritius/raw/econ/Digest_NA_Yr2024_180625.xlsx"
  local_econ_catalogue_root: "../catalogue"
  processed_local_catalogue_root: "../catalogue/datasets/mauritius/processed"
  processed_local_econ_data: "../catalogue/datasets/mauritius/processed/mus_gdp2024/mus.parquet"

local_econ:
  country_code: "MUS"
  year: 2024
  rupees_per_usd: 47.12

metadata:
  # Q: Do these paths need to be configurable (and therefore here) or rather hardcoded?
  layer: "workflow/layer.csv"
  hazard: "workflow/hazard.csv"

sensitivity:
  vars:
    # TODO: Some data structure, or path to a file containing data structure
    # describing how sensitive inputs might be varied, e.g.
    # - flood damage curve x shift (min & max?)
    # - wind damage curve y shift (min & max?)
    # - rehabilitation cost multiplier (min & max?)
    # - etc.
